environments:
pipelines:
  "yaml-example": # definition of yaml-example pipeline
    materials:
      mygit: # this is the name of material
        # keyword git says about type of material and url at once
        git: https://github.com/akshaykarle/gocd-yaml-config-example.git
        branch: master
    stages: # list of stages in order
      - build: # name of stage
          clean_workspace: true
          jobs:
              elastic_profile_id: "test"
              tasks:
               - exec: # indicates type of task
                   command: echo
                   arguments:
                    - "hello yaml"
