# simple.gocd.yaml
pipelines:
  pipe1:
    group: defaultGroup
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/akshaykarle/gocd-yaml-config-example.git
    stages:
      - build: # name of stage
          jobs:
            elastic_profile_id: "test"
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: make
